version: '3.7'
services:
  web:
    build: .
    container_name: apresentacao-frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URI: apresentacao-backend
    networks:
      - default
  backend:
    image: apresentacao-backend:latest
    container_name: apresentacao-backend
    ports:
      - "8080:8080"
    networks:
      - default