version: '3.7'
services:
  web:
    #build: .
    image: apresentacao-frontend
    container_name: apresentacao-frontend
    ports:
      - "81:80"
    volumes:
      #minikube
      #- /var/lib/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /var/lib/nginx/default.conf:/etc/nginx/conf.d/default.conf
      #- /var/lib/nginx/public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
  backend:
    image: apresentacao-backend:latest
    container_name: apresentacao-backend
    ports:
      - "8080:8080"
    networks:
      - default