version: '3.7'
services:
  web:
    #build: .
    image: apresentacao-frontend
    container_name: apresentacao-frontend
    ports:
      - "81:80"
    networks:
      - default
  backend:
    image: apresentacao-backend:latest
    container_name: apresentacao-backend
    ports:
      - "8080:8080"
    networks:
      - default