version: '3.7'
services:
  web:
    #build: .
    image: apresentacao-frontend:nginx
    container_name: apresentacao-frontend
    ports:
      - "81:80"
    volumes:
      - /var/lib/nginx/default.conf:/etc/nginx/conf.d/default.conf #configuracao minikube
      #- ./default.conf:/etc/nginx/conf.d/default.conf #configuracao local
    environment:
      - BACKEND_URI=apresentacao-backend
      - BACKEND_PORT=8080
    networks:
      - default
  backend:
    image: apresentacao-backend:java
    container_name: apresentacao-backend
    ports:
      - "8080:8080"
    volumes:
      #- /var/lib/logback/logback-logstash.xml:/etc/configuration/logback.xml #configuracao minikube
      #- /home/leandro/projetos/apresentacao-backend/src/kubernetes/logback-logstash.xml:/etc/configuration/logback.xml  #configuracao docker local
    networks:
      - default
    #environment:
    #  - LOGGING_CONFIG=file:/etc/configuration/logback.xml