apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: apresentacao-frontend-nginx
  name: config-map-apresentacao-frontend-nginx
  namespace: apresentacao
data:
  BACKEND_URI: service-apresentacao-backend
  BACKEND_PORT: "8080"
  NGINX_PORT: "8081"
