apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: apresentacao-frontend-node
  name: ingress-apresentacao-frontend-node
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: service-apresentacao-frontend-node
              servicePort: 3000