apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: apresentacao-frontend-node
  name: ingress-apresentacao-frontend-node
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: apresentacao-frontend.node #verificar host com cloud provider
      http:
        paths:
          - path: /*
            backend:
              serviceName: service-apresentacao-frontend-node
              servicePort: 3000