kind: Service
apiVersion: v1
metadata:
  labels:
    app: apresentacao-frontend-nginx
  name: service-apresentacao-frontend-nginx
spec:
  selector:
    app: apresentacao-frontend-nginx
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081